---
- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart nginx
  service: name=nginx state=restarted

- name: restart payment
  service: name=payment state=restarted

- name: restart benchworker
  service: name=benchworker state=restarted
