---
- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart golang
  service: name=isutrain-go state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: update-grub2
  shell: update-grub2
